on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
          
      - run: cd api && dotnet publish -c Release -o publish
      - uses: AkhileshNS/heroku-deploy@v3.13.15
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          usedocker: false
          appdir: "api"
        env:
          HD_JWT_KEY: ${{secrets._HD_JWT_KEY}}
          HD_pgconn: ${{secrets.HD_PGCONN}}
          HD_mqttToken: ${{secrets.HD_MQTTTOKEN}}
